apiVersion: v1
kind: Pod
metadata:
  name: local-disk-pod
  labels:
    app: nginx
spec:
  initContainers:
    - name: git-clone
      image: alpine/git
      command: ["git","clone","https://github.com/HighGooh/frontend.git","/app"]
      volumeMounts:
        - name: react-vol
          mountPath: /app
    - name: vite-build
      image: node:24.13.0-alpine3.22
      command: ["/bin/sh", "-c"]
      args:
        - |
          cd /app
          npm ci
          npm run build
          cp -r dist/* /app/
          cp -r default.conf /nginx/default.conf
      volumeMounts:
        - name: react-vol
          mountPath: /app
        - name: nginx-vol
          mountPath: /nginx
  containers:
    - name: nginx-container
      image: nginx:1.28
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: react-vol
      - mountPath: /etc/nginx/conf.d
        name: nginx-vol
  volumes:
    - name: react-vol
      emptyDir: {}
    - name: nginx-vol
      emptyDir: {}

---
apiVersion: v1
kind: Service

metadata:
  name: local-disk-service

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx