FROM uv:1

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-cache

COPY . .

EXPOSE 8001

# CMD ["uv","run","fastapi","run","main:app","--host","0.0.0.0","--port","8001"]
CMD ["uv", "run", "python", "-m", "fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8001"]