apiVersion: v1
kind: Service

metadata:
    name: app-sv

spec:
    type: NodePort
    selector:
        app: app-label
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30000