apiVersion: v1
kind: Pod
  
metadata:
  name: app-dp-59854c757
  labels:
    app: app-label

spec:
  containers:
    - image: nginx:1.28
      name: app-dp-59854c757
      imagePullPolicy: IfNotPresent 